Jasmine awesome
jalvar53/protractor-workshop-2017 pull request #14
Opened 2017-12-05 20:29 UTC by jalvar53

Adding jasmine-awesome-reporter the tests

2017-12-05 20:50 UTC, germandavid85 requested changes

2017-12-05 20:50 UTC, germandavid85 commented on protractor/helpers/awesome-report.ts
> +
remove extra line

2017-12-06 13:06 UTC, luigisamurai commented on src/page/ProductDetail.page.ts
> +    return $('[name="Submit"] > span');
review that this selector to be unique

2017-12-06 13:08 UTC, germandavid85 requested changes

2017-12-06 13:08 UTC, germandavid85 commented on protractor/headless.config.ts
> +    defaultTimeoutInterval: 120000,
remove this comman

2017-12-06 13:08 UTC, germandavid85 commented on src/page/ProductDetail.page.ts
> +    return $('[name="Submit"] > span');
this change is not part of the commit changes, it should go in a separate commit

2017-12-06 13:19 UTC, germandavid85 approved these changes

2017-12-06 13:20 UTC, merged